### ISSUE TITLE
Error running spring-batch-lightmin-server-sample 

### ISSUE THREAD

**Issue by krishnaaravacadreon** [tuxdevelop/spring-batch-lightmin-samples#1]
Open http://localhost:50100/jobs

2017-04-18 13:48:03.768 ERROR 78517 --- [io-50100-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet dispatcherServlet threw exception
org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'message' cannot be found on null

**Comment by tuxdevelop** [comment]
Hi,
the application.yaml

server:
  port: 50100
  servlet-path: /lightmin-server

exposes the sample server on port 50100 and servlet root /lightmin-server.

http://localhost:50100/lightmin-server/ will be the starting url.

Best Regards,

Marcel
